### ISSUE TITLE
kalinka-pub-plugin broken

### ISSUE THREAD

**Issue by jarmoni** [dcsolutions/kalinka#6]
Following occures when publishing to MQTT:

```
java.lang.AbstractMethodError: org.diehl.dcs.kalinka.pub.plugin.example.MqttMqttJmsMessagePublisher.publish(Ljava/lang/Object;Lorg/diehl/dcs/kalinka/springframework/kafka/core/KafkaTemplate;)V
	at org.diehl.dcs.kalinka.pub.plugin.KalinkaPubPlugin$1.send(KalinkaPubPlugin.java:71)
	at org.apache.activemq.broker.BrokerFilter.send(BrokerFilter.java:153)
	at org.apache.activemq.broker.BrokerFilter.send(BrokerFilter.java:153)
	at org.apache.activemq.security.AuthorizationBroker.send(AuthorizationBroker.java:226)
	at org.apache.activemq.broker.MutableBrokerFilter.send(MutableBrokerFilter.java:158)
	at org.apache.activemq.broker.TransportConnection.processMessage(TransportConnection.java:581)
	at org.apache.activemq.command.ActiveMQMessage.visit(ActiveMQMessage.java:768)
	at org.apache.activemq.broker.TransportConnection.service(TransportConnection.java:336)
	at org.apache.activemq.broker.TransportConnection$1.onCommand(TransportConnection.java:200)
	at org.apache.activemq.transport.MutexTransport.onCommand(MutexTransport.java:45)
	at org.apache.activemq.transport.mqtt.MQTTInactivityMonitor.onCommand(MQTTInactivityMonitor.java:162)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.sendToActiveMQ(MQTTTransportFilter.java:106)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.sendToActiveMQ(MQTTProtocolConverter.java:181)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTPublish(MQTTProtocolConverter.java:494)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:219)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
	at org.apache.activemq.transport.mqtt.MQTTCodec$1.onFrame(MQTTCodec.java:65)
	at org.apache.activemq.transport.mqtt.MQTTCodec.processCommand(MQTTCodec.java:90)
	at org.apache.activemq.transport.mqtt.MQTTCodec.access$400(MQTTCodec.java:26)
	at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:213)
	at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
	at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
	at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:217)
	at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
	at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
	at org.apache.activemq.transport.mqtt.MQTTCodec$4.parse(MQTTCodec.java:217)
	at org.apache.activemq.transport.mqtt.MQTTCodec$3.parse(MQTTCodec.java:179)
	at org.apache.activemq.transport.mqtt.MQTTCodec$2.parse(MQTTCodec.java:138)
	at org.apache.activemq.transport.mqtt.MQTTCodec.parse(MQTTCodec.java:76)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.processBuffer(MQTTNIOTransport.java:132)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.serviceRead(MQTTNIOTransport.java:120)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport.access$000(MQTTNIOTransport.java:43)
	at org.apache.activemq.transport.mqtt.MQTTNIOTransport$1.onSelect(MQTTNIOTransport.java:72)
	at org.apache.activemq.transport.nio.SelectorSelection.onSelect(SelectorSelection.java:98)
	at org.apache.activemq.transport.nio.SelectorWorker$1.run(SelectorWorker.java:118)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is caused by usage of shade-plugin. Modules must be organized in a different way.

**Comment by jarmoni** [comment]
Shading happens in last step now.
